
paths:
  inputs_dir: "inputs"
  outputs_dir: "outputs"

engine:
  symbols: ["BTCUSDT"]  #, "ETHUSDT", "SOLUSDT"
  months: ["2025-01","2025-02","2025-03","2025-04","2025-05","2025-06","2025-07"]
  train_months: 3
  test_months: 1
  step_months: 1

labels:
  barrier_up_atr: 60     # mirror tp_mult
  barrier_dn_atr: 20      # mirror sl_mult
  # give moves time to happen (12h–24h is reasonable for 1m BTC)
  timeout_bars_micro: 2880   # try 720 first; if still sparse, 1440

labels_mining:
  barrier_up_atr: 60       # easier for mining only (keeps 3:1 ratio)
  barrier_dn_atr: 20
  timeout_bars_micro: 2880 # 24h horizon to allow hits

bars:
  source: "inputs_1m"
  atr_window: 50
  macro_tf: "60min"
  meso_tf: "15min"
  micro_tf: "1min"

motifs:
  # ε calibration speed & tolerance
  eps_cal_sample_max: 1000   # cap number of train windows sampled per bank for ε (fast)
  eps_cal_pctile: 20         # looser ε for better matching stability
  # Optional: fix the exact features & order used for multivariate windows
  features:
    - ret_z
    - tsmom_slope_z
    - atr
    - atr_z
    - atr_pct_price
    - hv_ratio
    - bb_width_pct
    - impulse_score
    - atr_med
    - body_tr_ratio
    - wick_upper_tr
    - wick_lower_tr
    - clv
    - donchian_pos
    - dist_to_don_hi_atr
    - dist_to_don_lo_atr
    - prior_break_up_cnt
    - prior_break_dn_cnt
    - bars_since_high
    - bars_since_low
    - pullback_from_high_pct
    - pullup_from_low_pct
    - trend_r2_w60
    - adx_14
    - kama_slope
    - volume_z
    - tick_imbalance
  horizons:
    macro:
      L: 40
      top_k: 120
      keep: 40
      candidate_stride: 1
      hit_eps_pct_range: [5, 25]
      weight: 0.20
      freshness_bars: 12
    meso:
      L: 60
      top_k: 240
      keep: 80
      candidate_stride: 1
      hit_eps_pct_range: [5, 25]
      weight: 0.30
      freshness_bars: 15
    micro:
      L: 30
      top_k: 1200
      keep: 300
      candidate_stride: 1
      hit_eps_pct_range: [5, 25]
      weight: 0.50
      freshness_bars: 5

gating:
  require_macro: false     # was true
  require_meso:  false     # was true
  require_micro: true
  # match scores from MultiShapeletMatcher are typically ~0.05–0.30
  score_min: 0.12          # was 0.60; start lenient, tighten later
  pick_side: "argmax"
  bad_max: 0.95
  alpha: 0.10
  margin_min: -0.02
  discord_block_min: 0.995
  cooldown_bars: 30

risk:
  sl_mult: 20.0
  tp_mult: 60.0
  be_at_R: 0.65
  tsl:
    atr_mult: 20
    floor_from_median_mult: 1.1
    arm_after_secs: 15
    min_secs_between_steps: 20
    quantize_price: true

ui:
  progress: true
  progress_ascii: true
  progress_mininterval: 0.2
  simulate_debug_first_n: 0   # 0 = don’t print per-minute decisions
